server:
  port: 8082

spring:
  application:
    name: auth-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    listener:
      simple:
        default-requeue-rejected: false
  mongodb:
    uri: ${MONGODB_URL:mongodb://localhost:27017/auth_db}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000