server:
  port: 8080
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: flight-inventory-route
              uri: ${FLIGHT_SERVICE_URL}
              predicates:
                - Path=/api/flights/**

            - id: hotel-inventory-route
              uri: ${HOTEL_SERVICE_URL}
              predicates:
                - Path=/api/hotels/**

            - id: order-service-route
              uri: ${ORDER_SERVICE_URL}
              predicates:
                - Path=/api/orders/**

            - id: payment-service-route
              uri: ${PAYMENT_SERVICE_URL}
              predicates:
                - Path=/api/payments/**

            - id: auth-service-route
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/api/auth/**

            - id: user-service-route
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/api/users/**

            - id: api-composition-route
              uri: ${API_COMPOSITION_URL}
              predicates:
                - Path=/api/booking/**
  jwt:
    secret: ${JWT_SECRET}