server:
  port: 8080
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: flight-inventory-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/flights,/api/flights/**

            - id: hotel-inventory-route
              uri: http://localhost:8084
              predicates:
                - Path=/api/hotels,/api/hotels/**

            - id: payment-order-route
              uri: http://localhost:8085
              predicates:
                - Path=/api/orders,/api/orders/**

            - id: payment-service-route
              uri: http://localhost:8086
              predicates:
                - Path=/api/payments,/api/payments/**

            - id: auth-service-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth,/api/auth/**
  jwt:
    secret: ${JWT_SECRET}
