package org.booking.authservice.exception.dto;

public enum ErrorCode {
    USER_NOT_FOUND,
    INVALID_AMOUNT_WITHDRAW,
    SERVICE_UNAVAILABLE,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_EXISTS,
    VALIDATION_FAILED,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,
}
