server:
  port: 8083

spring:
  application:
    name: flight-inventory
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mongodb:
    uri: mongodb://localhost:27017/flight_db
  jwt:
    secret: ${JWT_SECRET}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans