server:
  port: 8087

spring:
  application:
    name: api-composition

services:
  order-service: ${ORDER_SERVICE_URL:http://localhost:8085}
  payment-service: ${PAYMENT_SERVICE_URL:http://localhost:8086}
  flight-service: ${FLIGHT_SERVICE_URL:http://localhost:8083}
  hotel-service: ${HOTEL_SERVICE_URL:http://localhost:8084}