server:
  port: 8080

spring:
  application:
    name: api-composition
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/order_db
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans