server:
  port: 8081

spring:
  application:
    name: api-composition
  jwt:
    secret: ${JWT_SECRET}


services:
  order-service: http://localhost:8085
  payment-service: http://localhost:8086
  flight-service: http://localhost:8083
  hotel-service: http://localhost:8084

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans